# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxyzoo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bar',
        ),
        migrations.DeleteModel(
            name='Bulge',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Odd',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
        migrations.DeleteModel(
            name='Prominence',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Sa',
        ),
        migrations.DeleteModel(
            name='Sa_num',
        ),
        migrations.DeleteModel(
            name='Tidal',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxyzoo.Parent'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
