# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxyzoo', '0002_auto_20160324_2052'),
        ('galaxyzoo', '0002_bar_bulge_edge_odd_parent_pattern_prominence_round_sa_sa_num_tidal'),
    ]

    operations = [
    ]
