# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxyzoo', '0004_auto_20160324_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='answer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bulge',
            name='answer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulge',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='edge',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='odd',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odd',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parent',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pattern',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prominence',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prominence',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='round',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sa',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sa',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sa_num',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sa_num',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tidal',
            name='answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tidal',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bar',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='bulge',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='odd',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='prominence',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sa_num',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tidal',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
