#PBS -q regular
#PBS -l mppwidth=1
#PBS -l walltime=08:00:00
#PBS -N run10
#PBS -l vmem=20GB
#PBS -e $PBS_JOBNAME.$PBS_JOBID.err
#PBS -o $PBS_JOBNAME.$PBS_JOBID.out
#PBS -A m2218
export LD_LIBRARY_PATH=/global/homes/d/dorislee/anaconda/lib:$LD_LIBRARY_PATH
cd /project/projectdirs/astro250/doris/halo/darksky_catalog
aprun -n 1 /global/homes/d/dorislee/anaconda/bin/python halo_catalog.py  10 >progress10.txt
